package com.laptrinhjavaweb.model;
// Generated Apr 18, 2021, 7:16:46 AM by Hibernate Tools 5.4.27.Final


/**
 * Comment generated by hbm2java
 */
public class Comment extends abstractnodel<Comment> {


    private Long newsId;
    private Long userId;
    private String content;

    public Long getNewsId() {
        return newsId;
    }

    public void setNewsId(Long newsId) {
        this.newsId = newsId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }


}