package com.laptrinhjavaweb.model;
// Generated Apr 18, 2021, 7:16:46 AM by Hibernate Tools 5.4.27.Final

/**
 * Role generated by hbm2java
 */
public class Role extends abstractnodel<Role> {


    private String name;
    private String code;


    public Role() {
    }


    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }


}
